<?xml version="1.0" encoding="utf-8"?><Database Name="IPv4" Class="IPv4DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=IPv4;Integrated Security=True" SettingsObjectName="IPCIDR.Properties.Settings" SettingsPropertyName="IPv4ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.IPv4SSL" Member="IPv4SSL">
    <Type Name="IPv4SSL">
      <Column Name="Address" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IP" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="RoundtripTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Issuer" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="Server" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="Isgxs" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Speed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdateTime" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>